version: '3.6'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/db/mysql_data:/var/lib/mysql
      - ./docker/db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 4406:3306
    container_name: books_mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: books_db
